dist: bionic

language: python

matrix:
  include:
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.8
      env: TOXENV=black,check-manifest,flake8

install:
  - "pip install tox"

script:
  - "tox"

branches:
  except:
    - debian

#notifications:
#  irc:
#    channels:
#      - "irc.freenode.org#mopidy"
#    on_success: change
#    on_failure: change
#    use_notice: true
#    skip_join: true
